export const torten = [
    {
        id: 1,
        name: 'Lotus-Karamell',
        beschreibung: 'Kuchen mit Lotus und Karamell',
        preis: 39.90,
        bildUrl: '/src/assets/images/Kuchen_Lotus-caramell.png',
    },
    {
        id: 2,
        name: 'Schoko-Ganache',
        beschreibung: 'Intensiver Schokoladenkuchen mit zarter Zartbitter-Ganache und einem Hauch Espresso.',
        preis: 42.50,
        bildUrl: '/src/assets/images/Kuchen_Schokolade.png',
    },
    {
        id: 3,
        name: 'Pistazien-Himbeer',
        beschreibung: 'Saftiger Pistazienboden kombiniert mit frischer Himbeercreme und leichter Mascarpone.',
        preis: 44.90,
        bildUrl: '/src/assets/images/Kuchen_pistazien-Himbeer.png',
    },
    {
        id: 4,
        name: 'Beeren-Sahne',
        beschreibung: 'Locker gebackener Vanilleboden mit einer Mischung aus Waldbeeren und fluffiger Sahnecreme.',
        preis: 37.90,
        bildUrl: '/src/assets/images/Kuchen_beeren-Sahne.png',
    },
    {
        id: 5,
        name: 'Karamell-Crunch',
        beschreibung: 'Saftiger Karamellkuchen mit knusprigem Topping',
        preis: 45.00,
        bildUrl: '/src/assets/images/Kuchen_karamell-crunch.png',
    },
    {
        id: 6,
        name: 'Zitrone-Mohn',
        beschreibung: 'Frischer Zitronenkuchen mit feinem Mohnaroma',
        preis: 39.90,
        bildUrl: '/src/assets/images/Kuchen_zitrone-mohn.png',
    },
    {
        id: 7,
        name: 'Mango-Cheesecake',
        beschreibung: 'Cremiger Frischkäsekuchen mit frischer Mangosauce',
        preis: 34.90,
        bildUrl: '/src/assets/images/Kuchen_mango-cheesecake.png',
    },
    {
        id: 8,
        name: 'Schoko-Erdnussbutter',
        beschreibung: 'Intensiver Schokokuchen mit salziger Erdnussbuttercreme',
        preis: 43.90,
        bildUrl: '/src/assets/images/Kuchen_schoko-erdnussbutter.png',
    },
    {
        id: 9,
        name: 'Honig-Mandel',
        beschreibung: 'Feiner Honigteig mit karamellisierten Mandeln',
        preis: 34.90,
        bildUrl: '/src/assets/images/Kuchen_honig-mandel.png',
    }
]